[package]
name = "http-proxy-impl"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
color-eyre = "0.6.5"
eyre = "0.6.14"
thiserror = "2.0.21"
tracing.workspace = true
tracing-subscriber = "0.3.23"

[workspace.dependencies]
tracing = "0.1"

[workspace.lints.clippy]
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"
expect_used = "deny"
enum_glob_use = "deny"
